### ISSUE TITLE
Dimension error about the `SequenceINN`

### ISSUE THREAD

**Issue by ffhibnese** [vislearn/FrEIA#161]
My input tensor is 18 x 512, so I initialize the SequenceINN with dim [18, 512]. And then I put a 1 x 18 x 512 tensor into the INN, and the process terminated and raised RuntimeError: mat1 and mat2 cannot be multiplied. 

Is there any mistake I made when I applied the related code?

**Comment by fdraxler** [comment]
Thanks for the question. Can you provide isolated code that shows how you construct your network, and a stack trace? This would greatly simplify finding the error.

**Comment by fdraxler** [comment]
Thanks for the code! The subnet constructor assumes that a tensor with one data dimension is passed, but the actual data is 2D. You need to use a subnetwork that can process such tensors, e.g. a [Conv1D](https://pytorch.org/docs/stable/generated/torch.nn.Conv1d.html)

**Comment by ffhibnese** [comment]
> Thanks for the code! The subnet constructor assumes that a tensor with one data dimension is passed, but the actual data is 2D. You need to use a subnetwork that can process such tensors, e.g. a [Conv1D](https://pytorch.org/docs/stable/generated/torch.nn.Conv1d.html)

Thanks for your clear reply, my problem is solved successfully!
