### ISSUE TITLE
[BUG] IndexError: tuple index out of range

### ISSUE THREAD

**Issue by mjack3** [vislearn/FrEIA#170]
Code to reproduce the bug

```
dims = (128, 28, 28)

branch = [InputNode(*dims)]
branch.append(Node(branch[-1], Fixed1x1Conv, {'M': torch.eye(128)}))
branch.append(OutputNode(branch[-1]))
inn = GraphINN(branch)

some_inputs = torch.rand(1, *dims)

inn(some_inputs)
```

The error is raised using the main branch of this repository.
The error in the following condition in line 209 in nodes.py

` if not torch.is_tensor(mod_jac) or mod_jac.shape[0] != out[0].shape[0]:
` 

Here, mod_jac is a number tensor value. So, it passes at the right side of the condition, where `mod_jac.shape[0]` is out of range

**Comment by mjack3** [comment]
Is there someone working on this repository?

**Comment by fdraxler** [comment]
Not so actively at the moment -- thanks for your patience.
