### ISSUE TITLE
RuntimeError: NVML_SUCCESS == r INTERNAL ASSERT FAILED at "/opt/pytorch/pytorch/c10/cuda/CUDACachingAllocator.cpp":830

### ISSUE THREAD

**Issue by NikhilMank** [vislearn/FrEIA#175]
- I am running a training code. It is running without any problem for 18853 iterations and then throwing this error. I have not written anything new at this point, the whole code was executed for many iterations before throwing this error.
- The graph network was operated in 'rev' mode starting from iter.No 12000
- I have tried to run the training code multiple times and the same error occured at the same iteration and same code line.
- I got the same error at different points with different batch_sizes. For batch_size = 8, the same error occured at around 17500 iterations. For batch_size = 16, the error occured at 18853 for three runs.

![image](https://github.com/vislearn/FrEIA/assets/41358516/9af8f109-7f97-4565-a1d9-148d04a29898)

The error is a direct cause from the code line of your library coupling block.

**Comment by fdraxler** [comment]
That’s a tough one, I have had success debugging such a case by training on the CPU and then obtaining a stack trace to the actual problem (CUDA can be nasty to debug given that it’s not synchronous), might also work with CUDA_LAUNCH_BLOCKING=1

**Comment by NikhilMank** [comment]
@fdraxler Thanks for reply, I will try running the code after setting CUDA_LAUNCH_BLOCKING=1 on the gpu

**Comment by NikhilMank** [comment]
@fdraxler I have tried training with CUDA_LAUNCH_BLOCKING=1 but the error message was same. I have now started training on CPU.

**Comment by NikhilMank** [comment]
@fdraxler Hi, I have ran it on CPU and observed that the loss values are becoming 0 after the failure point and there is a massive increase in the memory usage, I guess the values are shooting up. I have used a conv network as the constructor for GlowCouplingBlock. I am attaching the network which I have used as an image. I performed NLLLoss on this network. Do you think using CNN as constructor in GLOWCouplingBlock is causing any problem?

![image](https://github.com/vislearn/FrEIA/assets/41358516/261483d0-854d-42bb-8375-79b136f7a035)
![image](https://github.com/vislearn/FrEIA/assets/41358516/26f595fe-86ab-4839-bbee-683281183e43)
![image](https://github.com/vislearn/FrEIA/assets/41358516/c16ed5a8-1fc7-4164-a272-6285412f5f4d)
